name: Ajouter une relation
description: Ajouter une flèche ou double-flèche entre deux personnages
title: "[Ajouter] Relation : xxx"
labels: ["ajout","relation"]
body:
  - type: input
    id: nom1
    attributes:
      label: Perso 1
      placeholder: Uzumaki Naruto
    validations:
      required: true

  - type: input
    id: nom2
    attributes:
      label: Perso 2
      placeholder: Uchiha Sasuke
    validations:
      required: true

  - type: dropdown
    id: typeBversA
    attributes:
      label: Perso 1 > Perso 2
      options:
        - Affection
        - Amitié
        - Compliqué
        - Famile
        - Maître
        - Elève
        - Hostilité
        - Respect
        - Rivalité
        - Jalousie
        - Peur
    validations:
      required: true
      
  - type: dropdown
    id: typeBversA
    attributes:
      label: Perso 2 > Perso 1
      options:
        - Affection
        - Amitié
        - Compliqué
        - Famile
        - Maître
        - Elève
        - Hostilité
        - Respect
        - Rivalité
        - Jalousie
        - Peur
    validations:
      required: true
