name: Ajouter un personnage
description: Ajouter un jeton personnage au graphe
title: "[Ajouter] Personnage"
labels: ["ajout","personnage"]
body:
  - type: input
    id: nom
    attributes:
      label: Nom
      placeholder: Uzumaki Naruto
    validations:
      required: true

  - type: input
    id: avatar
    attributes:
      label: Avatar
      placeholder: https://xxx
    validations:
      required: true

  - type: input
    id: groupe
    attributes:
      label: Groupe
      placeholder: Kumo
    validations:
      required: true
      
  - type: input
    id: personnage_type
    attributes:
      label: Type
      placeholder: PJ
    validations:
      required: true
