name: Ajouter une relation
description: Ajouter une ligne Nom + Nom2 + Relation + Axe
title: "[Ajouter] Personnage"
labels: ["ajout","relation"]
body:
  - type: input
    id: nom
    attributes:
      label: Nom
      placeholder: Uzumaki Naruto
    validations:
      required: true

  - type: input
    id: nom2
    attributes:
      label: Nom2
      placeholder: Uchiha Sasuke
    validations:
      required: true

  - type: input
    id: relation
    attributes:
      label: Relation
      options:
        - Amitié
        - Amour
        - Rivalité
        - Jalousie
        - Haine
        - Peur
    validations:
      required: true
      
  - type: input
    id: direction
    attributes:
      label: Direction
      options:
        - >
        - x
        - <
    validations:
      required: true
