name: Ajouter un personnage
description: Ajouter un jeton personnage au graphe
title: "[Ajouter] Personnage"
labels: ["ajout","personnage"]
body:
  - type: input
    id: nom
    attributes:
      label: Nom
      placeholder: Naruto
    validations:
      required: true

  - type: input
    id: avatar
    attributes:
      label: Avatar
      placeholder: https://xxx
    validations:
      required: true

  - type: dropdown
    id: groupe
    attributes:
      label: Groupe
      options:
        - Homura
        - Kiri
        - Kumo
        - Errants
    validations:
      required: true
      
  - type: dropdown
    id: personnage_type
    attributes:
      label: Type
      options:
        - PJ
        - PNJ
    validations:
      required: true
